It looks like raw is safer than calling html_safe directly, because it casts to_s first.
  def raw(stringish)
    stringish.to_s.html_safe
  end

This eliminates this error: undefined method `html_safe' for nil:NilClass